Add stablelists to required EL8 build packages
Not having kernel-abi-stablelists causes e.g.

  error: Failed build dependencies:
        kernel-abi-whitelists is needed by zfs-kmod-2.1.5-1.el8.x86_64

when following the section on building kABI-tracking kmods.